main_app/urls.py
######

from django.urls import path, re_path
from .views import BookDetailView, BookListView, AuthorDetailView, AuthorListView, HomeView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main_app'

urlpatterns = [
    path('', HomeView.as_view(),name='home'),
    path('book/<int:pk>/', BookDetailView.as_view(), name='book-detail'),
    path('books/', BookListView.as_view(), name='book-list'),
    path('author/<int:pk>/', AuthorDetailView.as_view(), name='author-detail'),
    path('authors/', AuthorListView.as_view(), name='author-list'),
]




######


#app_name = 'main_app'

#urlpatterns = [
   #path('', home_view.as_view(),name='home'),
   # path('projects/', projects_view.as_view(),name='projects'),
   # path('travel/', travel_view.as_view(),name="travel"),
   # path('thank_you/', thankyou_view.as_view(),name="thank_you"),
   # path('contact/', ContactFormView.as_view(), name="contact"),
   # path('article/<int:pk>', traveldetail_view.as_view(), name="article-detail"),
   # path('aboutme/', aboutme_view.as_view(),name='aboutme'),
   #path('readings/', readings_view.as_view(),name='readings'),
   # path('book/<int:pk>', bookdetail_view.as_view(),name='book-detail'),
#]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models 
from django.contrib.auth.models import User
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns


class Author(models.Model):
    name = models.CharField(max_length=100)
    born_year = models.IntegerField(null=True, blank=True)
    death_year = models.IntegerField(null=True, blank=True)
    biography = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='images', null=True, blank=True)
    

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
          return f'/author/{self.id}/' #('author-detail', args=[str(self.id)])

class Book(models.Model):
    title = models.CharField(max_length=255)
    # Foreign Key used because book can only have one author, but authors can have multiple books    
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    pages = models.PositiveIntegerField(null=True, blank=True)
    genre = models.CharField(max_length=50, blank=True, null=True)
    rating = models.PositiveSmallIntegerField(null=True, blank=True)
    year_published = models.IntegerField(null=True, blank=True)
    year_read = models.IntegerField(null=True, blank=True)
    summary = models.TextField(max_length=5000, help_text="Enter a brief description of the book", blank=True)
    my_thoughts = models.TextField(max_length=10000, blank=True, default="")
    coverimage = models.ImageField(null=True, upload_to='images', blank=True)
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)

    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
        null=True,
        blank=True,
    )

main_app/views.py
# Create your views here.

from django.shortcuts import render
#from django.http.response import HttpResponse
from django.views.generic import TemplateView,FormView,CreateView, DetailView, ListView
#from main_app.forms import ContactForm
from .models import Book, Author


class HomeView(ListView):
    template_name = 'main_app/Home.html'
    model = Book


class BookDetailView(DetailView):
    model = Book
    template_name = 'main_app/BookDetails.html'

class AuthorDetailView(DetailView):
    model = Author
    template_name = 'main_app/AuthorDetails.html'

class BookListView(ListView):
    model = Book
    template_name = 'main_app/BookList.html'
    paginate_by = 3




class AuthorListView(ListView):
    model = Author
    template_name = 'main_app/AuthorList.html'
    context_object_name = 'authors'
    paginate_by = 10




#class readings_view(ListView):
 #   model = Book
  #  template_name = 'main_app/readings.html'
   # paginate_by = 25

    
#class bookdetail_view(DetailView):
 #   model = Book
  #  template_name = 'main_app/book_details.html'

#class travel_view(ListView):
#    model = Post
#    template_name = 'main_app/travel.html'

#class traveldetail_view(DetailView):
#    model = Post
#    template_name = "main_app/travel_details.html"




#class projects_view(TemplateView):
#    template_name = 'main_app/projects.html'


#class thankyou_view(TemplateView):
#    template_name = 'main_app/thank_you.html'

#class ContactFormView(FormView):
#    form_class = ContactForm
#    template_name = 'main_app/contact.html'

        # URL NOT a Template.html
#    success_url = "/main_app/thank_you/"
#    
#    def form_valid(self,form):
#        print(form.cleaned_data)
#        return super().form_valid(form)

#class aboutme_view(TemplateView):
#    template_name = 'main_app/aboutme.html'
    

templates/Base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/main_app/Master.css' %}">

    <title>Regan Jones</title>

</head>

<body>

    <!-- SITE HEADER -->
    <header class="home-header">
        <a class="profile-pic" href="{% url 'main_app:home' %}"><img  src="{% static 'main_app/CTPP.png' %}" class="img-fluid" alt="Profile Picture" /></a>
        <h1>Regan Jones</h1>
    </header>
    {% block content %}

    
    {% endblock %}



  <!-- SITE FOOTER -->
  <footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6>About</h6>
          <p class="text-justify"> This is my personal page where I share updates on my adventures, projects and life. 
          <br> This website is an exercise in discipline . It is meant to be a repository where I can share thoughts and doings. The intention is to scale my expression. All while, building out a skill set that can support future endeavors.</p>
          <aside><p><small> Any one thing is easy, it is the order of operations that which is difficult.</small></p></aside> 
          
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Categories</h6>
          <ul class="footer-links">
            <li><a href="{% url 'main_app:book-list' %}">Books</a></li>
            <li><a href="{% url 'main_app:author-list' %}">Authors</a></li>
          </ul>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Quick Links</h6>
          <ul class="footer-links">
            <li><a href="#">Privacy Policy</a></li>   
            <li><a href="#">About Me</a></li>
          </ul>   
        </div>
      </div>
      <hr>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">Copyright &copy; 2023 All Rights Reserved by 
       <a href="#">Regan</a>.
          </p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

templates/main_app/AboutMe.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>About Me</h1>


{% endblock %}

templates/main_app/AuthorDetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'main_app/AuthorDetails.css' %}">



<main class="author-profile">
  <header class="author-header">
    <h1 class="author-name">{{ author.name }}</h1>
    {% if author.image %} 
    <img class="author-image" src="{{ author.image.url }}" alt="Image Not Found"> 
    {% endif %}
  </header>
  <section class="author-info">
    <div class="author-details">
      <p class="author-birth-date">Birth Date: {{ author.born }}</p>
      {% if author.death %}
      <p class="author-death-date">Death Date: {{ author.death }}</p>
      {% endif %}
    </div>
    <p class="author-biography">Biography: {{ author.biography }}</p>
  </section>
  <a class="back-link" href="{% url 'main_app:book-list' %}">Back</a>
</main>



{% endblock %}

templates/main_app/AuthorList.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'main_app/AuthorList.css' %}">

<main>
  <section class="author-section">
    <header class="author-header">
      <h1 class="author-header-title">List of Authors</h1>
    </header>
    <div class="author-list-container">
      <ul class="author-list">
        {% for author in object_list %}


        <li class="author-list-item">

          <div class="author-title-flex">
            <a href="{% url 'main_app:author-detail' author.pk %}" class="author-list-link">{{ author.name }}</a>
            {% if author.image %}
               <img class="author-list-cover" src="{{ author.image.url}}" alt="Image Not Found">
            {% endif %}
          </div>
          
          <p class="author-biography">{{ author.biography }}</p>
          
        </li>


        {% endfor %}
      </ul>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

    
  </section>
</main>
  
{% endblock %}

templates/main_app/BookDetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'main_app/BookDetails.css' %}">




<main class="book-detail">
      <section class="book-info">

        <header class="book-header">
          <h1 class="book-title">{{ book.title }}</h1>
          <h2 class="book-author"> By: <a href="{{ book.author.get_absolute_url }}"> {{ book.author }}</a></h2>
          {% if book.coverimage %} 
            <img class="book-cover-image" src="{{book.coverimage.url}}" alt="Image Not Found"> 
          {% endif %}   
        </header>

            <div>
              <dl class="book-details-flex">
                <dt>Date Published:</dt>
                <dd>{{ book.date_published }}</dd>
                <dt>ISBN:</dt>
                <dd>{{ book.isbn }}</dd>
                <dt>Pages:</dt>
                <dd>{{ book.pages }}</dd>
                <dt>Genre:</dt>
                <dd>{{ book.genere }}</dd>
              </dl>
            </div>
 
            <div class="book-summary">
              <h3>Book Summary:</h3>
              <p>{{ book.summary }}</p>
            </div>

            <div class="book-thoughts">
              <h4>My Thoughts:</h4>
              <dl>
                <dt><small>Read Date: {{ book.date_read }}</small></dt>
                <dd><p>{{ book.my_thoughts }}</p></dd>
              </dl>
            </div>
            
      </section>

    <a class="back-link" href="{% url 'main_app:home' %}" >Back</a> 
</main>
{% endblock %}

templates/main_app/BookList.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<link rel="stylesheet" href="{% static 'main_app/BookList.css' %}">




<main>
    <section class="book-list">
      <header class="header">
        <h1 class="header-title">Welcome to my Online Book Shelf!</h1>
        <p class="header-desc">I like organization and I like my bookshelf. However, I can't put my audiobooks anywhere physically, and I don't feel obligated to buy a hard copy every time I finish an audiobook. Hence, the online bookshelf. Here I can store all of my book titles, reflections, and anything else I may want.</p>
      </header>
      <div class="book-list-container">
        <ul class="book-list-items">
            {% for book in object_list %}
                <li class="book-list-item">
                    <a class="book-list-link" href="{% url 'main_app:book-detail' book.pk %}">{{ book.title }}</a> - {{ book.author }}<br>
                </li>
                <li>
                    {% if book.coverimage %} 
                    <img class="book-list-cover" src="{{book.coverimage.url}}" class="img-fluid" alt="Image Not Found"> 
                    {% endif %}
                </li>
                <li>
                    <p class="book-list-summary">{{ book.summary }}</p>
                </li>
            {% endfor %}
        </ul>
      </div>
   


      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
      </div>
    </section>
</main>
{% endblock %}

templates/main_app/Home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<link rel="stylesheet" href="{% static 'main_app/Home.css' %}">

<main>
    <header class="book-header-flex">
        <h1 class="header-title">Welcome to my Online Book Shelf!</h1>
        
    </header>
    <section class="book-list-container">
        <p class="header-desc">I like organization and I like my bookshelf. However, I can't put my audiobooks anywhere physically, and I don't feel obligated to buy a hard copy every time I finish an audiobook. Hence, the online bookshelf. Here I can store all of my book titles, reflections, and anything else I may want.</p>
        <ul class="book-list-items">
            {% for book in object_list %}
                <li class="book-list-item">
                    {% if book.coverimage %} 
                    <a href="{% url 'main_app:book-detail' book.pk %}"><img class="book-list-cover" src="{{book.coverimage.url}}" class="img-fluid" alt="Image Not Found"> </a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </section>
</main> 

{% endblock %}